### ISSUE TITLE
Memory corruption playbin no unsafe

### ISSUE THREAD

**Issue by rikte88** [sdroege/gstreamer-rs#70]
A combination of bus.timed_pop(), msg.get_src(), and playbin.set_state() causes a GStreamer-CRITICAL error which makes no sense when looking at the code. The error is followed by lots of memory corruption (lots of errors in valgrind). No unsafe code is needed. The bug cannot be reliably triggered, but repeatedly changing the state does the trick. The shortest example I could come up with to make it occur is attached, and valgrind output obtained with:
valgrind ./target/debug/binary > valgrind-output.txt 2>&1

[corruption-example.zip](https://github.com/sdroege/gstreamer-rs/files/1604266/corruption-example.zip)

Tested on latest stable Fedora and Debian, same result. Deleted Cargo.lock, used:
 "gstreamer 0.10.1 (registry+https://github.com/rust-lang/crates.io-index)",
Used:
stable-x86_64-unknown-linux-gnu (default)
rustc 1.23.0 (766bd11c8 2018-01-01)

**Comment by sdroege** [comment]
Thanks for reporting! I'll take a look soon.

If you say you deleted Cargo.lock, does this mean an older version worked correctly?

**Comment by sdroege** [comment]
From the valgrind output, my best guess is that this is another floating reference issue. Maybe we get a floating reference in the autoplug-* signal handler but we're not supposed to actually own it. That would be a bug in GStreamer. Which version are you using of GStreamer and gst-plugins-base? I remember some possibly related fixes recently.

I'll try to reproduce myself once I'm at a computer again.

**Comment by sdroege** [comment]
Never mind, the analysis makes no sense as you don't use any of those signals. Will check later

**Comment by rikte88** [comment]
gstreamer1.0-plugins-base is already the newest version (1.10.4-1).

I am not certain how long the bug has existed, at least for some weeks. I noticed silent deadlocks in a much larger project at times when playing/pausing/switching songs. (again no unsafe, no mutexes)

Thanks for the great work! I always wanted proper gstreamer bindings for Rust!

**Comment by sdroege** [comment]
1.12.4 is actually the latest version, but probably not in any stable distro releases. I'll check with that, git master and 1.10.5. Thanks for the info


Let me know if you run into any other problems :)

**Comment by sdroege** [comment]
I can reproduce it with 1.10.5 but not with 1.12.4. Happens actually quite fast with 1.10.5, less than 5s. So it's going to be a GStreamer bug that was fixed at some point between 1.10.5 and 1.12.4.

My best guess is that it's these 3 commits that fix it:
https://cgit.freedesktop.org/gstreamer/gst-plugins-base/commit/gst/playback/gstplaybin2.c?id=b4899a5a6575bd62786174d225a58c0f86499d13
https://cgit.freedesktop.org/gstreamer/gst-plugins-base/commit/gst/playback/gstplaybin2.c?id=2372894c633da7fac947f3e149c5a51a074a94cb
https://cgit.freedesktop.org/gstreamer/gst-plugins-base/commit/gst/playback/gstplaybin2.c?id=2ec51ef998caa7530ff2caf8c7025b883d7f6f04

**Comment by rikte88** [comment]
Thank you very much for verifying. It seems I was wrong about fedora, I had problems reproducing the simplified version on Fedora too but the full project still crashes.

I modified the simplified example so that it crashes on fedora too (gstreamer 1.12.4), however it takes significantly longer to crash. It seems likely that the problem(s) originates in gstreamer...

Logs and updated example are attached.
[crash-example2.zip](https://github.com/sdroege/gstreamer-rs/files/1604881/crash-example2.zip)


Last metadata expiration check: 0:41:24 ago on Thu 04 Jan 2018 10:09:34 PM CET.
Package gstreamer1-1.12.4-1.fc27.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by sdroege** [comment]
Thanks for the new testcase, I'll try later

**Comment by sdroege** [comment]
FWIW, you can do `playbin.set_property("uri", &"http:/....").unwrap()`. No need to manually create a Value

**Comment by sdroege** [comment]
For me it always fails after a short while with

```
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `Failure`,
 right: `Failure`', src/main.rs:68:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Nothing found in valgrind until that point. Can you also run with G_DEBUG=fatal_warnings G_SLICE=always-malloc and make sure to have debug packages for libc6, glib, gstreamer and the plugins installed? Maybe I can understand what's happening from a valgrind log then.

**Comment by sdroege** [comment]
Closing this for now as there's nothing actionable here. Also this is most likely a bug in GStreamer, there's nothing in the bindings that could cause memory corruption here like this. So please file a bug here: https://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer
